-- Daily analytics + payment granularity

ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'TRANSFER_ACCOUNT_1';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'TRANSFER_ACCOUNT_2';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'NEQUI';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'CREDIT_CARD';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'CREDIT';

ALTER TABLE "SiteConfig"
  ADD COLUMN IF NOT EXISTS "dailySalesGoal" DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "creditTermDays" INTEGER NOT NULL DEFAULT 15;

ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "analyticsCategory" TEXT,
  ADD COLUMN IF NOT EXISTS "analyticsSubcategory" TEXT;
